update dockerfile
soramitsu/iroha2-longevity-load-rs pull request #12
Opened 2022-05-25 15:57 UTC by BAStos525

# Task

[SUP-945]: docker_restarting_container stage1 iroha2, instance: iroha2-stage1-s5

## Changes

1. add docker multistage build to compile RUST binary inside image.

## Author

Signed-off-by: Vasilii Zyabkin <zyabkin@soramitsu.co.jp>

2022-05-26 01:05 UTC, wpi86 requested changes

2022-05-26 01:05 UTC, wpi86 commented on Dockerfile
> +    chown -R iroha ${LOAD_DIR}
Are your executables immutable?

2022-06-01 00:24 UTC, wpi86 approved these changes

2022-06-01 05:34 UTC, f33r0 approved these changes

2022-06-05 12:32 UTC, Cre-eD commented on Dockerfile
> +     ${LOAD_DIR}
```suggestion
     /home/rust/src/target/x86_64-unknown-linux-musl/release/iroha2-longevity-load-rs .
```

2022-06-05 12:33 UTC, Cre-eD commented on Dockerfile
> +ENV PORT 8084
why is it in the end and no `=` sign?

2022-06-11 10:29 UTC, Cre-eD commented on Dockerfile
> +    mkdir -p ${LOAD_DIR}
```suggestion
RUN apk --update --no-cache add ca-certificates && \
    adduser --disabled-password --gecos "" iroha --shell /bin/bash --home /app && \
    mkdir -p ${LOAD_DIR}
```

2022-06-12 19:31 UTC, Cre-eD approved these changes

2022-06-13 11:12 UTC, merged