DOPS-1683: Check iroha2 dependencies in Cargo.toml
soramitsu/iroha2-longevity-load-rs pull request #17
Opened 2022-07-20 20:15 UTC by BAStos525

# Task

[DOPS-1683]:  Implement iroha2 longevity script dependencies auto checking from hyperledger repository.

## Issue
Currently we added dependabot for. But dependencies for `iroha_clienta` and `iroha_data_model` can not be checked by dependabot. Every time developers have to update it manually and they often forget to do it in time.

## Changes

1. Add GH Action workflow to check for a new `iroha_data_model` and `iroha_client` versions from root Hyperledger repository and create a PR then.

## Possible improvements
It is better to make this workflow on `dispatch` event and move to `dev` and `release` branches. But firstly we need to take an agreement with iroha2-dev team about new changes in their Hyperledger CI. Perhaps, we will do it in [DOPS-1682](https://soramitsu.atlassian.net/jira/software/c/projects/DOPS/boards/43?modal=detail&selectedIssue=DOPS-1862&assignee=611c97b0a3e00f006875887b)

## Author

Signed-off-by: Vasilii Zyabkin <vzyabkin@soramitsu.co.jp>

2022-07-21 06:01 UTC, wpi86 requested changes

2022-07-21 06:01 UTC, wpi86 commented on .github/workflows/update-dependencies.yaml
> +          find: version = "2.0.0-pre-rc.*"
I'm not sure if this is the correct regex, will it work for 2.0.1...?

2022-07-21 06:01 UTC, wpi86 commented on .github/workflows/update-dependencies.yaml
> +          find: version = "2.0.0-pre-rc.*" }
same

2022-07-21 07:27 UTC, BAStos525 commented on .github/workflows/update-dependencies.yaml
> +          find: version = "2.0.0-pre-rc.*"
Actually for a long time, `"2.0.0-pre-rc.(n)"` just the only one symbol that is changed. No one knows when version will be changed to 2.(n).(n) or even get rid off from `pre-rc`. But right, it's better to have a more unified pattern.

2022-07-22 07:43 UTC, Cre-eD approved these changes

2022-07-22 07:45 UTC, Cre-eD commented on .github/workflows/update-dependencies.yaml
> +          find: version = ".*-pre-rc.*"
so now you want to look for all new pre-release candidates? doesn't make a sense

2022-07-22 07:46 UTC, Cre-eD requested changes
fix the pattern

2022-07-24 17:30 UTC, BAStos525 commented on .github/workflows/update-dependencies.yaml
> +          find: version = ".*-pre-rc.*"
Not to pre-rc candidates exactly, I want to find any iroha version that could be in line 3th, and 9th and 10th then because I have to rename its version. But do not touch, for example, line 14 where here is also `some version` but not iroha. Assume that `version = "2..."` will be for a long time, we can do smth like that:
![image](https://user-images.githubusercontent.com/66615487/180658955-26190361-ba12-4deb-8137-f83415babba2.png)

2022-07-25 05:33 UTC, Cre-eD approved these changes
test it, then merge

2022-07-25 05:57 UTC, wpi86 commented on .github/workflows/update-dependencies.yaml
> +          find: version = ".*-pre-rc.*"
Maybe you should use something like https://github.com/marketplace/actions/toml-editor instead of regex?

2022-07-27 13:17 UTC, wpi86 approved these changes

2022-07-27 14:22 UTC, merged